### ISSUE TITLE
Classifications other than spam?

### ISSUE THREAD

**Issue by maxerickson** [jremillard/osm-changeset-classification#1]
For example, https://www.openstreetmap.org/changeset/56304628 dragged an intersection node (https://www.openstreetmap.org/node/346371832 ), a not all that uncommon error, but it also isn't spam or vandalism.

**Comment by jremillard** [comment]
It can do other kinds of classification, but the plan is to only pay attention to the tags, ignoring the geometry.  Dragging a node would not be detected.
